[package]
name = "funfunfun"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
bs58 = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.133"
solana-sdk = "2.3.1"
spl-token = "6.0.0"
base64 = "0.22.1"
env_logger = "0.11.7"